version: '3.0'

name: attendance
services:
  db:
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - app-network
  api:
    image: attendance:latest
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres:
